### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by this-toops** [qq15725/egami#1]
前端资源跨域问题

**Comment by qq15725** [comment]
是图片还是字体资源，可以再多提供点信息吗？错误信息也可以！

**Comment by RayaneSlimani** [comment]
Chrome : Ok 
Firefox : [modern-screenshot] Failed to parse web font css DOMException: CSSStyleSheet.cssRules getter: Not allowed to access cross-origin stylesheet
