### ISSUE TITLE
The rendered image has a text cloning bug.

### ISSUE THREAD

**Issue by om3rcan** [qq15725/egami#23]
When the image is downloaded on iOS devices, a font problem occurs and there are two texts. 

The image is as follows:

![xxx](https://user-images.githubusercontent.com/60554415/235488404-4b319dad-ad7e-499c-9d88-f4a9fc9bdef0.jpg)

**Comment by qq15725** [comment]
I need a minimal reproduction to debug your issue, thanks!

[Playground for https://codesandbox.io](https://codesandbox.io/s/modern-screenshot-lxhrev?file=/index.html)

[Playground for https://codepen.io](https://codepen.io/qq15725/pen/VwGeqwa)

[Playground for https://play.vuejs.org](https://play.vuejs.org/#eNplkk1rg0AQhv/KsFBqIFFpycWYQA899FAIpb3tZdGNmrof7I75IPjfO64mDeSguO++88y7417Ym7XxoZMsY7kvXGMRvMTObrhulDUO4QKlUd9mqyvoYeeMgmdlSun0gvxSal8bfL5zO7mbg9GfptMoy1sN9SAX14XRHsEZg+8trAd3NLuqpUDx8/XxL3N9A0XCn3UB0QzWG7hwDVd3fBBtJ6lGHEVDjClsNLYYd+eUyxeilRm8QE/g4cmT8cB0VFqgVLYVKGkFkJfNYciw5mzEcAZFK7yfBM6CjYzeCr3ZtuJcOcpZEnMQAiMhSGDTd6MqyLwrqH6KTUSP51aSgk5ovzNOZWPIKI2XMwjqkChaLNOnOQzv2YrKEoLmyV1eWgZUaBsP+cYBARybEusMXtPUnlajVMumqvFe68MoAoDN2fgfF0rYeO+NpnsRWHza8JxlVzpnDxdh2OWsRrQ+S5JO298qLoxKHow0HI9Jo0t5itWeqFOSnvV/3hTgRw==)
